### ISSUE TITLE
Support the new zig package manager

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [Hejsil/mecha#55]
Since mecha does not compile to an actual library, it can't be used as a module using the zig package manager

**Comment by Hejsil** [comment]
I'm not sure how you're trying to use the package manager, but I have [one program](https://github.com/Hejsil/lemonbar-maker) that depends on mecha through the package manager. See [build.zig.zon#L9-L12](https://github.com/Hejsil/lemonbar-maker/blob/61624dfb0b0dde969490f2b1a7da2091dec57078/build.zig.zon#L9-L12) and [build.zig#L25-L35](https://github.com/Hejsil/lemonbar-maker/blob/61624dfb0b0dde969490f2b1a7da2091dec57078/build.zig#L25-L35). Perhaps this needs to be documented better. I'm not sure how Zig documents how the package manager should be used.

**Comment by Hejsil** [comment]
Without any further detail I cannot really do much with this issue. Closing
