### ISSUE TITLE
Release for zig 0.13

### ISSUE THREAD

**Issue by jonasdiemer** [Hejsil/mecha#62]
Hi,

just tried mecha 0.8 with zig 0.13 via zig package manager - fails to build due to incompatibility. Works with head, so wondering if we can release that is compatible with 0.13. Thanks!

Regards

**Comment by Hejsil** [comment]
Aah right. Zig had a new release and I forgot. Give me a moment and I'll tag a new release :)

**Comment by Hejsil** [comment]
Yea, just made sure everything works. https://github.com/Hejsil/mecha/releases/tag/0.9.0
