### ISSUE TITLE
Adding toTaggedStruct

### ISSUE THREAD

**Issue by bigs** [Hejsil/mecha#63]
Hey @Hejsil!

I'm new to Zig and working on an IRC bot to work my way around (it's my programming language onboarding project of choice). I came across your library and have been enjoying it, as I'm a big ole FP nerd. In my project, I came across a case where I wanted to conveniently write parsers for instances of a tagged union...

```zig
const MsgTypes = enum {
  privmsg,
  notice,
  join,
  // etc
};

const IrcMsg = union(MsgTypes) {
  privmsg: struct {
    sender: []const u8,
    target: []const u8,
    message: []const u8,
  },
  // etc
}
```

I wanted to use `toStruct`, but that couldn't handle the nesting. So I wrote a function `toTaggedStruct` (naming suggestions welcome) that allows you to make a parser on the order of...

```zig
const parse_privmsg = mecha.combine(some, parsers, here).map(toTaggedStruct(IrcMsg, MsgType.privmsg));
```

I have two questions:

1. Would you welcome the contribution of this function?
2. How can I get the current master branch to compile 😅 I suppose that's the real question right now... I get the following error:

```
➜  mecha git:(bigs/to-tagged-union-struct) zig build test
/Users/bigs/Code/mecha/build.zig:44:58: error: root struct of file 'Build.Step' has no member named 'MakeOptions'
            fn make(_: *std.Build.Step, _: std.Build.Step.MakeOptions) anyerror!void {
                                           ~~~~~~~~~~~~~~^~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/Build/Step.zig:1:1: note: struct declared here
id: Id,
^~
referenced by:
    readMeStep: /Users/bigs/Code/mecha/build.zig:52:10
    build: /Users/bigs/Code/mecha/build.zig:27:20
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Are you working off of a new RC of Zig in the master branch?

**Comment by Hejsil** [comment]
> Would you welcome the contribution of this function?

Yea this seems like something worthwhile to add. `toUnion` seems like a better name :)

> Are you working off of a new RC of Zig in the master branch?

The master branch of mecha is made to compile with latest Zig master for now

**Comment by bigs** [comment]
I'll tidy that up :)
