### ISSUE TITLE
Parsing error reporting with line and character numbers

### ISSUE THREAD

**Issue by joelreymont** [Hejsil/mecha#71]
How would I implement parse failure reporting with line and character numbers?

Any suggestions?

**Comment by Hejsil** [comment]
It is something that can be hand rolled, but it becomes complicated very fast as it is not built into mecha. There has been issues before asking for similar things

https://github.com/Hejsil/mecha/issues/41
https://github.com/Hejsil/mecha/issues/54

**Comment by joelreymont** [comment]
What about building it into mecha?

The usability is atrocious at the moment, e.g. I can't venture to guess which of the combinators failed when my tests fail.

Why not model it on [chumsky](https://github.com/zesterer/chumsky)?

**Comment by Hejsil** [comment]
> Why not model it on [chumsky](https://github.com/zesterer/chumsky)?

Sure, but it requires that someone puts in the work. I'm not really using mecha myself at the moment, so there is not much motivation for me to do a large scale refactor of the library for stuff like this.

**Comment by joelreymont** [comment]
Let's keep this issue open if you don't mind.

**Comment by joelreymont** [comment]
Do you accept PRs?

**Comment by Hejsil** [comment]
> Do you accept PRs?

Yea and I'll take the time for proper review and getting it merged if it looks good :+1:

**Comment by joelreymont** [comment]
PR #73 should do it.

**Comment by joelreymont** [comment]
PR #74 didn't do it either but I have high hopes for PR #76!
